// "use client"
import "@/app/styles/globals.css";
// import { Provider } from "react-redux";
// import { store } from "./store";

import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import Providers from "./Provider";
// import { Poppins } from 'next/font/google'

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['300','400','500','600','700'],
//   variable: '--font-poppins' // optional for CSS usage
// })


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (

    <html lang="en">
      <body className="min-h-screen bg-gray-100">
        <Providers>
          {children}
          <ToastContainer
          />
        </Providers>
      </body>
    </html>

  );
}
