"use client"
import "@/app/styles/globals.css";
import { Provider } from "react-redux";
import { store } from "./store";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className="min-h-screen bg-gray-100">
          {children}
        </body>
      </html>
    </Provider>
  );
}
