"use client"
import "@/app/styles/globals.css";
import { Provider } from "react-redux";
import { store } from "./store";
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className="min-h-screen bg-gray-100">
        <Provider store={store}>
          {children}
          <ToastContainer
          />
        </Provider>
      </body>
    </html>

  );
}
